// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const generateApiKey = `-- name: GenerateApiKey :one
INSERT INTO api_keys(name, api_key, user_id)
VALUES($1, $2, $3)
RETURNING id, name, api_key, user_id, created_at, revoked_at, last_used_at
`

type GenerateApiKeyParams struct {
	Name   string
	ApiKey string
	UserID uuid.UUID
}

func (q *Queries) GenerateApiKey(ctx context.Context, arg GenerateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, generateApiKey, arg.Name, arg.ApiKey, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.UserID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}
