// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const followFeeds = `-- name: FollowFeeds :one

INSERT INTO feed_follows(user_id, feed_id)
VALUES ($1, $2)
RETURNING id, user_id, feed_id, created_at, updated_at
`

type FollowFeedsParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) FollowFeeds(ctx context.Context, arg FollowFeedsParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, followFeeds, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFollowedFeeds = `-- name: GetFollowedFeeds :many
SELECT id, user_id, feed_id, created_at, updated_at FROM feed_follows
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetFollowedFeeds(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
